version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: blog-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - blog-network

  backend:
    build: ./server
    container_name: blog-backend
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://172.31.42.158:27017/blogdb
    ports:
      - "5001:5001"
    networks:
      - blog-network
    command: [ "sh", "-c", "sleep 10 && npm start" ]  # Wait for MongoDB to be ready

  frontend:
    build: ./client
    container_name: blog-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local

