apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2  # ✅ High availability with two instances
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: blog-app-deployment_frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80  # ✅ Since Nginx runs on port 80 inside the container
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80         # ✅ External service port (Kubernetes)
      targetPort: 80   # ✅ Matches Nginx inside the container
      nodePort: 30080  # ✅ Manually setting NodePort for access
  type: NodePort

